### PR TITLE
fix: Document and automate release and versioning steps

### LINKED ISSUE #874: Modify the release process to enforce the versioning standards discussed in 811
Discussion:
  https://github.com/konveyor/pelorus/discussions/811

Features:
  * Clear release process documentation to enforce versioning standards as discussed in the #811 
  * Scripts and tooling to allow repeatable creation of the pelorus-operator, pelorus-operator-bundle and exporters (example: grafana operator version is the same as in OLM dependencies)

Requirements: 
  - [x] release validation
    - [x] Include validation to ensure our pelorus-operator has proper version
    - [x] ensure the consistency of the versions within helm-charts
        - [x] helm-charts versions between source and the operator should be consistent and the same #885
        - [x] versions of the prometheus and grafana within helm-charts and the operator OLM dependencies should be in sync
  - [x] release doc
    - [x] Release process for all Pelorus artifacts: 
      - [x] Pelorus-Operator tags / sha / versions [quay.io/pelorus](https://quay.io/organization/pelorus)
        - [x] Pelorus Operator Version
        - [x] Pelorus Operator Bundle Version
      - [x] Pelorus-Operator Marketplace [redhat-openshift-ecosystem/community-operators-prod](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/pelorus-operator)
        - [x] Pelorus Operator tags / sha / versions
      - [x] Helm charts versions
        - [x] pelorus
        - [x] exporters
        - [x] operators
      - [x] exporter image tags / sha [quay.io/pelorus](https://quay.io/organization/pelorus)
        - [x] pelorus-deploytime-exporter
        - [x] pelorus-failure-exporter
        - [x] pelorus-committime-exporter
        - [x] pelorus-release-exporter
        - [x] pelorus-webhook-exporter
      - [x] GitHub Pelorus [releases and tagging](https://github.com/konveyor/pelorus/releases) process
  - [x] developer doc
    - [x]  versioning during development cycle (pre-release)
  - [x] scripts and/or CI jobs to ensure no manual version editing is in place and the process is as automated as possible for both release and developer use cases.
    - [x] Create quay images for Pelorus Operator and PR in openshift community-operators-prod repo when a release PR is merged

### PR DESCRIPTION
**Pull request by mateusoliveira43**
- [x] I have read [Pelorus Contributing guidelines](https://github.com/dora-metrics/pelorus/blob/master/CONTRIBUTING.md)

## Linked Issues

resolves #874

## Description

Document and automate steps related to versioning/release.

## Testing Instructions

Run the new script with different options and check if they give the expected results.

### CODE REVIEW

File: scripts/create_release_pr.sh [hunk 1]
```diff
@@ -36,13 +36,11 @@
 #   |   v2.0.8-rc.4   |      -z       |       v2.0.8      |
 #   |     v2.0.8      |      -n       |     v2.0.9-rc.1   |
 #   |   v2.0.8-rc.4   |      -n       |     v2.0.8-rc.5   |
-#   |   v2.0.8-rc.4   | -v 4.1.2-rc.7 |     v4.1.2-rc.7   |
```
Comment (mpryc) [inline scripts/create_release_pr.sh:39]: I was using this exact versions few times, when things were needed to be fixed or to just produce versions which I could store in my private quay registry, how to do this now?

File: scripts/create_pelorus_operator.sh [hunk 2]
```diff
@@ -40,27 +40,43 @@ function print_help() {
...
     printf "\t  -d\tpath to destination folder, default: %s\n" "${DEFAULT_PELORUS_OPERATOR_DIR}"
-    printf "\t  -f\tforce, removes destination folder that must be named pelorus-operator before proceeding\n"
     printf "\t  -p\tpath to DIR with operator patches to be applied, default: %s\n" "${DEFAULT_PELORUS_OPERATOR_PATCHES_DIR}"
-    printf "\t  -v\toperator version to be used in a format x.y.z. If not set z+1 is used.\n"
     printf "\t  -o\tQuay user/org name, default to pelorus, which is the production storage.\n"
+    printf "\t  -f\tforce, removes destination folder that must be named pelorus-operator before proceeding\n"
+    printf "\t  -x\tbump X part of the version (Y and Z are set to 0, so X.0.0)\n"
+    printf "\t  -y\tbump Y version (Z will start at 0, so X.Y.0)\n"
+    printf "\t  -z\tbump Z version (Z in the X.Y.Z)\n"
+    printf "\t  -n\tbump RC number (N in X.Y.Z-rc.N)\n"
```
Comment (mpryc) [inline scripts/create_pelorus_operator.sh:49]: how about `-r` ?

File: scripts/chart-test.sh [hunk 3]
```diff
@@ -34,7 +34,7 @@ fi
 # Runs chart-testing (ct CLI) with remote flag to avoid git errors
 
 ct lint --remote "$REMOTE" --config ct.yaml || exit 1
-rm charts/pelorus/charts/*.tgz
+rm charts/pelorus/charts/*.tgz &> /dev/null
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply scripts/chart-test.sh:37]: changing to use flag `-f, --force           ignore nonexistent files and arguments, never prompt`.

Added this because I have run it once and the tgz file was not created and command complained the file did not exist

File: scripts/create_pelorus_operator.sh [hunk 4]
```diff
@@ -136,19 +151,43 @@ pushd "${destination_dir}" || exit 2
...
+    OPERATOR_MAKEFILE_IN_MASTER="$(curl https://raw.githubusercontent.com/dora-metrics/pelorus/master/pelorus-operator/Makefile 2> /dev/null)"
+    OPERATOR_VERSION_IN_MASTER=$(echo "$OPERATOR_MAKEFILE_IN_MASTER" | grep "VERSION ?= " | cut -c 12-)
+    # shellcheck disable=SC2207
+    CURRENT_VERSION_ARRAY=( $(echo "$OPERATOR_VERSION_IN_MASTER" | sed "s/-rc//g" | tr ' . '  '  ') )
+    V_X_VER=${CURRENT_VERSION_ARRAY[0]}
+    V_Y_VER=${CURRENT_VERSION_ARRAY[1]}
+    V_Z_VER=${CURRENT_VERSION_ARRAY[2]}
+    V_RC_VER=${CURRENT_VERSION_ARRAY[3]}
+
+    RC_SUFFIX=""
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply scripts/create_pelorus_operator.sh:167]: I think bash is not good for this kind of thing

I can merge them on this PR to avoid duplication, or wait to do what I want to do, that is rewrite all complex bash scripts in Python or other language, in another task

[the remark this answers is not in the document]
Comment (mpryc) [reply scripts/create_pelorus_operator.sh:167]: Ok that's fine. I will be ok to merging with duplication, but how about small python helper script to include such function ?

File: scripts/chart-test.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (mpryc) [reply scripts/chart-test.sh:37]: right, so you could use `-f`, but if the file can not be removed even with `-f` flag we won't know why. As I wrote, wrong owner or permissions that prevents to remove the file by the current user. Not big deal as it probably won't happen with the normal usage.

File: .github/workflow_templates/create-market-place-pr/main.py [hunk 5]
```diff
@@ -0,0 +1,36 @@
...
+            # TODO write better descriptions after tests
+            title="Automation test - DELETE IT",
+            body="This is an automation test, this PR will be closed without merging\n@mateusoliveira43 @mpryc",
+            base="main",
+            head=f"{settings.input_fork}:pelorus-operator-{settings.input_version}",
+            maintainer_can_modify=True,
+            # TODO remove draft?
+            draft=True,
+        )
+        pull_request.create_comment("/hold")
```
Comment (mateusoliveira43) [inline .github/workflow_templates/create-market-place-pr/main.py:32]: @mpryc opening the PR with hold is enough, right? No need to create it as draft as well, I mean

File: .github/workflows/cd.yml [hunk 6]
```diff
@@ -0,0 +1,118 @@
+name: Continuous Delivery - Operator
```
Comment (mateusoliveira43) [inline .github/workflows/cd.yml:1]: @mpryc I have tested the job in my fork, example of created PR https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2690

File: scripts/update-projects-version.py [hunk 7]
```diff
@@ -0,0 +1,375 @@
+#!/usr/bin/env python3
```
Comment (mateusoliveira43) [inline scripts/update-projects-version.py:1]: @mpryc please test out this script, once validated I will delete `scripts/create_release_pr.sh`, `scripts/specify_operator_update.py` and `scripts/create_pelorus_operator.sh` and use this one to do their job

File: scripts/create_release_pr.sh (hunk 1 above)
Comment (mateusoliveira43) [reply scripts/create_release_pr.sh:39]: I really want to remove this option, if we have written everything correctly, we do not need that option

File: scripts/create_pelorus_operator.sh (hunk 4 above)
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply scripts/create_pelorus_operator.sh:167]: merged the 3 scripts in a python one

File: scripts/chart-test.sh [hunk 8]
```diff
@@ -81,3 +81,31 @@ if ! grep \""$PROMETHEUS_VER_HELM"\" pelorus-operator/bundle/metadata/properties
...
+CURRENT_CHART_VERSION_RC_VER=${CURRENT_CHART_VERSION_ARRAY[1]}
+# shellcheck disable=SC2207
+CURRENT_OPERATOR_VERSION_ARRAY=( $(echo "$CURRENT_OPERATOR_VERSION" | tr ' \-rc '  '  ') )
+CURRENT_OPERATOR_VERSION_RC_VER=${CURRENT_OPERATOR_VERSION_ARRAY[1]}
+if [ "$CURRENT_CHART_VERSION_RC_VER" != "$CURRENT_OPERATOR_VERSION_RC_VER" ]; then
+  echo "ERROR: Release candidate versions differs between charts (rc$CURRENT_CHART_VERSION_RC_VER) and operator (rc$CURRENT_OPERATOR_VERSION_RC_VER)!"
+  exit 1
+fi
+
+# TODO check for pending releases
```
Comment (mateusoliveira43) [inline scripts/chart-test.sh:110]: I think this TODO is wrong

we should automatically do a github release after a version without `rc` is merged

I think that is possible, just need to read the draft release body

do you agree with me?

File: scripts/update-projects-version.py [hunk 9]
```diff
@@ -0,0 +1,375 @@
...
+    )
+    pelorus_operator_image_tags.add_header("Authorization", "Bearer XYZ")
+    with request.urlopen(pelorus_operator_image_tags) as response:
+        tags: List[Dict[str, str]] = list(json.load(response)["tags"])
+    tag_names = [
+        tag["name"]
+        for tag in tags
+        if tag.get("end_ts") is None and not tag["name"].upper().isupper()
+    ]
+    tag_names.sort(reverse=True)
```
Comment (mateusoliveira43) [inline scripts/update-projects-version.py:278]: This needs improving the logic, like first converting to a semver object, and then running sort

File: .github/workflow_templates/create-market-place-pr/Dockerfile [hunk 10]
```diff
@@ -0,0 +1,7 @@
+FROM python:3.11
+
+RUN pip install "pydantic==1.5.1" "pygithub==1.58.0"
```
Comment (mpryc) [inline .github/workflow_templates/create-market-place-pr/Dockerfile:3]: Should this be via some sort of requierments that is updated by our dependentbot ? This can be bind mounted during creation of such pip install.

File: .github/workflow_templates/create-market-place-pr/main.py (hunk 5 above)
Comment (mateusoliveira43) [reply .github/workflow_templates/create-market-place-pr/main.py:32]: tried to add the label directly (instead of commenting `/hold`) but the account running it needs adm privileges from the repo to be able to do it

File: scripts/chart-test.sh (hunk 8 above)
Comment (mateusoliveira43) [reply scripts/chart-test.sh:110]: did not understand, can you give an example?

File: .github/workflow_templates/create-market-place-pr/Dockerfile (hunk 10 above)
Comment (mateusoliveira43) [reply .github/workflow_templates/create-market-place-pr/Dockerfile:3]: I think yes, but I would create a separate repo just for it (example https://github.com/tiangolo/latest-changes), to be separate (we do not need `pygithub` for any development step, for example) 

I would put this as a future refactor task, do you agree?

File: .github/workflow_templates/create-market-place-pr/action.yml [hunk 11]
```diff
@@ -0,0 +1,15 @@
...
+description: Create PR in redhat-openshift-ecosystem/community-operators-prod from fork
+inputs:
+  token:
+    description: Token that has write access to fork repo
+    required: true
+  version:
+    description: The operator version to be released
+    required: true
+  fork:
+    description: The username of the fork to open PR from
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply .github/workflow_templates/create-market-place-pr/action.yml:11]: It should be a user username (in this case I am using mine, but it should be a bot account). So the user (not a ORG) must already have the fork created (created by itself and with the same name as the original repo) to run it

Did you understand now? How should be a better description written to avoid misleading in the future?

File: .github/workflows/cd.yml [hunk 12]
```diff
@@ -0,0 +1,118 @@
...
+      - master
+    paths:
+      - 'exporters/**'
+      - 'charts/**'
+      - 'pelorus-operator/**'
+      - '.github/workflows/cd.yml'
+
+env:
+  # TODO create bot account
+  FORK: mateusoliveira43
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply .github/workflows/cd.yml:17]: I am not wanting it to be run from who triggered the job, it should be run always by the same user (in this case mine, that is already setup, but it should be a bot account in the future)

File: .github/workflows/cd.yml [hunk 13]
```diff
@@ -0,0 +1,118 @@
...
+      #   run: |
+      #     git config user.name github-actions # TODO create bot account
+      #     git config user.email github-actions@github.com # TODO create bot account
+      #     git add -A
+      #     git commit --signoff -m "operator pelorus-operator (${{ needs.setup.outputs.version }})"
+      #     git push origin pelorus-operator-${{ needs.setup.outputs.version }}
+
+      - name: Create PR
+        # TODO change to upstream repo and master branch
+        uses: "mateusoliveira43/pelorus/.github/workflow_templates/create-market-place-pr@fix/release-steps-and-automation"
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply .github/workflows/cd.yml:114]: because I do not want to clone the repo here just to use this file (I do clone in the openshifty repo on this job, not ours)

it was my user just to test out, it will run against our ORG and master

File: scripts/create_release_pr.sh [hunk 14]
```diff
@@ -206,26 +192,33 @@ if [ "$NO_VERSIONS" -ne 1 ]; then
...
-# docs/Development.md should have exactly 2 places with the updated version
+# _deploymentconfig.yaml should have exactly  only one version updated
 NO_VERSIONS=$(grep -c "v$SEMVER" "$DEPLOYMENTCONFIG_PATH")
 if [ "$NO_VERSIONS" -ne 1 ]; then
   echo "ERROR: Unexpected changes in the: $DEPLOYMENTCONFIG_PATH"
   exit 1
 fi
 
-printf "\nIMPORTANT:\n\t Update the operator files using ./scripts/create_pelorus_operator.sh script.\n\n"
+helm dep update charts/pelorus &> /dev/null
```
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply scripts/create_release_pr.sh:211]: added this check to the new Python script

File: scripts/chart-test.sh (hunk 8 above)
Comment (mpryc) [reply scripts/chart-test.sh:110]: Example. Create the release now regardless of any other conditions, based on the current state of the files and version that is taken from the source or passed while creating tag. Then we can have action that is creating tag as a link between closing PR and releasing new version of operator.

File: .github/workflow_templates/create-market-place-pr/Dockerfile (hunk 10 above)
Comment (mpryc) [reply .github/workflow_templates/create-market-place-pr/Dockerfile:3]: ok just add TODO somewhere so we don't forget.

File: scripts/update-projects-version.py (hunk 7 above)
Comment (mpryc) [inline scripts/update-projects-version.py:1]: A new script should include Copyright header and some description on what it does, how it works.

File: scripts/update-projects-version.py [hunk 15]
```diff
@@ -0,0 +1,375 @@
...
+            pattern=VERSION_PATTERN,
+            new=next_chart_version,
+            number_of_changes=2,
+        )
+        logging.info("IMPORTANT: this change will result in a new release")
+    logging.info("Update finished successfully")
+
+
+if __name__ == "__main__":
+    parser = argparse.ArgumentParser(
```
Comment (mpryc) [inline scripts/update-projects-version.py:329]: Please move the arg parser into separate function. For small no. of options it's ok to put it inside main, however here for clarity I prefer to move it to separate one as the list of items is growing and has some grous, e.g. example from other project:

https://github.com/rhos-infra/devnest/blob/master/devnest/lib/cli.py#L102

File: scripts/update-projects-version.py [hunk 16]
```diff
@@ -0,0 +1,375 @@
...
+    run_command(
+        "oc get crd grafanas.integreatly.org",
+        error_message="Grafana CRD not found",
+    )
+    run_command(
+        "oc get crd prometheuses.monitoring.coreos.com",
+        error_message="Prometheus CRD not found",
+    )
+
+    if destination.is_file():
```
Comment (mpryc) [inline scripts/update-projects-version.py:101]: The checks for the destination empty/not empty should happen before running any commands that goes outside of local box, e.g. `oc auth` they are faster and quicker to respond on the error.

File: scripts/update-projects-version.py [hunk 17]
```diff
@@ -0,0 +1,375 @@
...
+    parser.add_argument(
+        "-f",
+        "--force",
+        action="store_true",
+        help="Removes destination folder before proceeding.",
+    )
+    group = parser.add_mutually_exclusive_group(required=True)
+    group.add_argument(
+        "-x",
+        "--major",
```
Comment (mpryc) [inline scripts/update-projects-version.py:349]: We don't have an option to set major version for pelorus-operator without bumping major version of charts?
What if we want to create:
pelorus-operator: 1.0.0
chart-versions: just a minor release ?

File: scripts/update-projects-version.py [hunk 18]
```diff
@@ -0,0 +1,375 @@
...
+        help="Major update to project versions.",
+    )
+    group.add_argument(
+        "-y",
+        "--minor",
+        action="store_true",
+        help="Minor update to project versions.",
+    )
+    group.add_argument(
+        "-z",
```
Comment (mpryc) [inline scripts/update-projects-version.py:360]: Same here and for the pre-release, we are forcing someone to bump both versions which isn't always necessary. I think it's perfectly valid scenario to keep the helm charts on the next patch release with a new minor release of pelorus-operator.

There was a long discussion about versioning and we never said a major bump of one (helm or operator) will require major bump of another:

https://github.com/dora-metrics/pelorus/discussions/811#discussioncomment-5062792

File: scripts/update-projects-version.py [hunk 19]
```diff
@@ -0,0 +1,375 @@
...
+    logging.info("Update finished successfully")
+
+
+if __name__ == "__main__":
+    parser = argparse.ArgumentParser(
+        description="Update all versions of the project.",
+        allow_abbrev=False,
+    )
+    parser.add_argument(
+        "-d",
```
Comment (mpryc) [inline scripts/update-projects-version.py:334]: `-d` should never allow the `-f`, we can think of very dangerous operation here while using this script with some other shell args...  (don't try the below command):

```
./scripts/update-projects-version.py -z -f -d /
```

File: scripts/update-projects-version.py [hunk 20]
```diff
@@ -0,0 +1,375 @@
...
+        tag["name"]
+        for tag in tags
+        if tag.get("end_ts") is None and not tag["name"].upper().isupper()
+    ]
+    tag_names.sort(reverse=True)
+
+    add_replaces_to_csv(
+        new_version=next_operator_version,
+        cluster_service_version_file=destination
+        / "bundle/manifests/pelorus-operator.clusterserviceversion.yaml",
```
Comment (mpryc) [inline scripts/update-projects-version.py:283]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 21]
```diff
@@ -0,0 +1,375 @@
...
+    )
+
+    logging.info(f"Updated operator available at {destination}")
+
+
+def main(arguments: argparse.Namespace) -> None:
+    check_prerequisites(destination=arguments.destination)
+
+    next_chart_version = get_next_version(
+        file="charts/pelorus/Chart.yaml",
```
Comment (mpryc) [inline scripts/update-projects-version.py:294]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 22]
```diff
@@ -0,0 +1,375 @@
...
+        software="chart",
+        arguments=arguments,
+    )
+    update_charts_folder(
+        next_chart_version=next_chart_version,
+    )
+
+    next_operator_version = get_next_version(
+        file="pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml",
```
Comment (mpryc) [inline scripts/update-projects-version.py:303]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 23]
```diff
@@ -0,0 +1,375 @@
...
+        next_operator_version=next_operator_version,
+        destination=arguments.destination,
+    )
+
+    if arguments.major:
+        logging.info('IMPORTANT: label your PR with "major"')
+    if arguments.minor:
+        logging.info('IMPORTANT: label your PR with "minor"')
+    if not arguments.pre_release:
+        documentation_file = ROOT / "docs/Development.md"
```
Comment (mpryc) [inline scripts/update-projects-version.py:317]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 24]
```diff
@@ -0,0 +1,375 @@
...
+        / "config/manifests/bases/pelorus-operator.clusterserviceversion.yaml",
+        pattern="    containerImage: placeholder",
+        new=f"    containerImage: {operator_image}:{next_operator_version}",
+        number_of_changes=1,
+    )
+    logging.info("Executing operator make bundle")
+    run_command("make bundle", directory=destination)
+
+    pelorus_operator_image_tags = request.Request(
+        "https://quay.io/api/v1/repository/pelorus/pelorus-operator/tag/"
```
Comment (mpryc) [inline scripts/update-projects-version.py:268]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 25]
```diff
@@ -0,0 +1,375 @@
...
+    )
+
+    for file in PATCHES_FOLDER.rglob("*"):
+        if file.is_file():
+            logging.info(f"Applying patch {file}")
+            run_command(f"patch -d {destination} -p0 < {file}")
+
+    replace_in_file(
+        file=PELORUS_OPERATOR_FOLDER
+        / "config/manifests/bases/pelorus-operator.clusterserviceversion.yaml",
```
Comment (mpryc) [inline scripts/update-projects-version.py:259]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 26]
```diff
@@ -0,0 +1,375 @@
...
+    for file in exporters_charts_in_operator.parent.glob("*.tgz"):
+        file.unlink()
+
+    replace_in_file(
+        file=PELORUS_OPERATOR_FOLDER / "Makefile",
+        pattern=r"VERSION \?= 0\.0\.1",
+        new=f"VERSION ?= {next_operator_version}",
+        number_of_changes=1,
+    )
+    operator_image = f"quay.io/{OPERATOR_ORGANIZATION_NAME}/{OPERATOR_NAME}"
```
Comment (mpryc) [inline scripts/update-projects-version.py:239]: move quay.io to something we can configure, I would like sometimes to push to local registry for example.

File: scripts/update-projects-version.py [hunk 27]
```diff
@@ -0,0 +1,375 @@
...
+
+def update_operator_folder(next_operator_version: str, destination: Path) -> None:
+    logging.info("Creating operator init files")
+    # TODO run update command instead of init every time
+    run_command(
+        f"operator-sdk init --plugins=helm --domain={OPERATOR_DOMAIN} --project-name={OPERATOR_NAME}",
+        directory=destination,
+    )
+    logging.info("Creating operator api")
+    exporters_charts_in_operator = destination / "helm-charts/pelorus/charts/exporters"
```
Comment (mpryc) [inline scripts/update-projects-version.py:221]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 28]
```diff
@@ -0,0 +1,375 @@
...
+    for file, occurrences in CHARTS_FILES_TO_UPDATE.items():
+        replace_in_file(
+            file=file,
+            pattern=VERSION_PATTERN,
+            new=next_chart_version,
+            number_of_changes=occurrences,
+        )
+
+    run_command(f"helm dep update {PELORUS_CHARTS_FOLDER}")
+    tar_files = (PELORUS_CHARTS_FOLDER / "charts").glob("*.tgz")
```
Comment (mpryc) [inline scripts/update-projects-version.py:183]: Is this also skipped in .gitignore? Do we really need to remove the tgz if it's not in github?

File: scripts/update-projects-version.py [hunk 29]
```diff
@@ -0,0 +1,375 @@
...
+
+    logging.info(run_command("operator-sdk version").stdout.strip())
+
+
+def get_version_upstream(file: str) -> semver.VersionInfo:
+    current_version = None
+
+    response: HTTPResponse
+    with request.urlopen(
+        f"https://raw.githubusercontent.com/dora-metrics/pelorus/master/{file}"
```
Comment (mpryc) [inline scripts/update-projects-version.py:123]: Move this to some constant var

File: scripts/update-projects-version.py [hunk 30]
```diff
@@ -0,0 +1,375 @@
...
+        exit_error(f"Patches folder {PATCHES_FOLDER} does not exist")
+
+    for dependency in SHELL_DEPENDENCIES:
+        if shutil.which(dependency) is None:
+            exit_error(
+                f"{dependency} executable not found, activate the project virtual environment"
+            )
+
+    run_command(
+        "oc auth can-i '*' '*' --all-namespaces",
```
Comment (mpryc) [inline scripts/update-projects-version.py:85]: We could check if the env is from our dev-env and if it's not then just warn that we recommend all the tooling to be from the .venv generated by make dev-env, otherwise someone may be using older versions of the tools etc...

File: scripts/update-projects-version.py [hunk 31]
```diff
@@ -0,0 +1,375 @@
...
+        "oc get crd prometheuses.monitoring.coreos.com",
+        error_message="Prometheus CRD not found",
+    )
+
+    if destination.is_file():
+        exit_error("Destination must be a folder, not a file")
+
+    if arguments.force and destination.exists():
+        logging.info(f"Removing destination folder {destination}")
+        shutil.rmtree(destination)
```
Comment (mpryc) [inline scripts/update-projects-version.py:106]: I really want to have some (y/n) user input here, before proceeding:

```
        are_you_sure = input(f"Do you really want to remove all the files from {destination} ?")
```

**Review by mpryc — CHANGES_REQUESTED** [review]

File: scripts/update-projects-version.py (hunk 31 above)
Comment (mpryc) [reply scripts/update-projects-version.py:106]: Or do some other safe check, e.g. in the previous implementation was:
https://github.com/dora-metrics/pelorus/blob/master/scripts/create_pelorus_operator.sh#L111

File: scripts/update-projects-version.py (hunk 17 above)
Comment (mateusoliveira43) [reply scripts/update-projects-version.py:349]: No, we do not have

I think this is not important at the moment, I can add a TODO for the future

File: scripts/update-projects-version.py (hunk 28 above)
Comment (mateusoliveira43) [reply scripts/update-projects-version.py:183]: Now that will be automated, I think it is safe, but I would still remove it, to know exactly what we are shipping with the operator

File: scripts/update-projects-version.py (hunk 18 above)
Comment (mpryc) [reply scripts/update-projects-version.py:360]: We could release major version of pelorus-operator with minor version bump of helm charts for example. We should never release one with rc version of another.

File: .github/workflows/cd.yml [hunk 32]
```diff
@@ -0,0 +1,108 @@
...
+          git config user.name github-actions # TODO create bot account
+          git config user.email github-actions@github.com # TODO create bot account
+          git add -A
+          git commit --signoff -m "operator pelorus-operator (${{ needs.setup.outputs.version }})"
+          git push origin pelorus-operator-${{ needs.setup.outputs.version }}
+
+      - name: Create PR
+        uses: "dora-metrics/pelorus/.github/workflow_templates/create-market-place-pr@master"
+        with:
+          token: ${{ secrets.FORK_USER_TOKEN }}
```
Comment (mateusoliveira43) [inline .github/workflows/cd.yml:106]: TODO for myself: add it to repo secrets

File: scripts/chart-test.sh (hunk 8 above)
Comment (mateusoliveira43) [reply scripts/chart-test.sh:110]: I am going to open a separate issue for this, already worked too much in this PR

File: .github/workflow_templates/create-market-place-pr/action.yml (hunk 11 above)
[the remark this answers is not in the document]
Comment (mateusoliveira43) [reply .github/workflow_templates/create-market-place-pr/action.yml]: TODO for myself: add how to create token some where

**Review by mpryc — DISMISSED** [review]
/lgtm

Tested update_projects_version.py in few different scenarios and I am happy with it! Thanks.

File: .github/workflows/cd.yml [hunk 33]
```diff
@@ -0,0 +1,108 @@
...
+  create-pr:
+    runs-on: ubuntu-latest
+    if: ${{ fromJSON(needs.setup.outputs.is_release) }}
+    needs: [setup, create-images]
+    steps:
+      - name: Checkout marketplace code
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ env.FORK_USER }}/community-operators-prod
+          token: ${{ secrets.FORK_TOKEN }}
```
Comment (mateusoliveira43) [inline .github/workflows/cd.yml:75]: forgot to change secret name here :grimacing:
